# vim: set ft=ruby

devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPad Pro (9.7-inch)",
  "iPad Pro (11-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)"
])

languages(["ja"])

# clear_previous_screenshots true
test_without_building true

project "Scrapmd.xcodeproj"
scheme "ScrapmdUITests"

derived_data_path './DerivedData'
namespace_log_files true
erase_simulator true
concurrent_simulators false
