name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    container: atsnngs/danger-swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Danger
      run: npx --package danger danger-swift ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
