name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    container: atsnngs/danger-swift:latest
    steps:
    - uses: actions/checkout@v1
    - run: danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
