name: Upload Screenshots

on:
  push:
    branches: [master]
    paths: ['fastlane/screenshots/*/*.png']

env:
  FASTLANE_SKIP_UPDATE_CHECK: 1
  DELIVER_USERNAME: ${{ secrets.APPLE_ID_EMAIL }}
  FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

jobs:
  upload:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: cache-bundler
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle config set path 'vendor/bundle'
    - run: bundle install
      if: steps.cache-bundler.outputs.cache-hit != 'true'
    - run: bundle exec fastlane release_screenshots
